### PR TITLE
add support for Apple Workflow files

### PR DESCRIPTION
**Pull request by idleberg**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

Add file-extension for Apple Workflow (`.wflow`) files

### CODE REVIEW

**Comment by 50Wliu** [comment]
Like #72, can you please provide some documentation?  The only wflow file I could find was binary.

**Comment by idleberg** [comment]
If you're on macOS, take a look at `/System/Library/Services`. I have several `.workflow` folders inside, each containing `Contents\document.wflow`. Also, Microsoft Office installs several workflows in the Documents folder.

It's mentioned [here](https://developer.apple.com/reference/automator/1566971-nserror_codes/amworkflowpropertylistinvaliderror?language=objc) that `wflow` is a property list, which is XML. However, that makes me wonder how you currently treat the more common `.plist` files, since they are not supported by this package.

Example:

https://github.com/sparanoid/automator-workflows/blob/master/Add%20%403x%20Suffix.workflow/Contents/document.wflow

**Comment by 50Wliu** [comment]
If they're plist, they should be added to atom/language-plist instead.

**Comment by Alhadis** [comment]
How come we have two separate grammars for an XML-based format?

**Comment by 50Wliu** [comment]
Looks like the plist grammar is just a thin wrapper around the xml grammar.

**Comment by Alhadis** [comment]
I was wondering if it had anything to do with [matching specific identifiers](https://github.com/atom/language-property-list/blob/master/grammars/property%20list%20(xml).cson#L451-L465) used in property-lists.

**Pull request closed without merging**
